using System.Runtime.Serialization;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: IMLC/IMLCProtocolBuffer.proto
namespace IMLC.IMLCProtocolBuffer
{
  [DataContract, global::ProtoBuf.ProtoContract(Name = @"StackTraceElement_PB")]
  public partial class StackTraceElement_PB : global::ProtoBuf.IExtensible
  {
    public StackTraceElement_PB() {}
    
    private string _class_name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"class_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string class_name
    {
      get { return _class_name; }
      set { _class_name = value; }
    }
    private string _method_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"method_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string method_name
    {
      get { return _method_name; }
      set { _method_name = value; }
    }
    private string _file_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"file_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string file_name
    {
      get { return _file_name; }
      set { _file_name = value; }
    }
    private int _line_number = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"line_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int line_number
    {
      get { return _line_number; }
      set { _line_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }

  [DataContract, global::ProtoBuf.ProtoContract(Name = @"Exception_PB")]
  public partial class Exception_PB : global::ProtoBuf.IExtensible
  {
    public Exception_PB() {}
    
    private readonly global::System.Collections.Generic.List<StackTraceElement_PB> _stack_trace_element = new global::System.Collections.Generic.List<StackTraceElement_PB>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stack_trace_element", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<StackTraceElement_PB> stack_trace_element
    {
      get { return _stack_trace_element; }
    }
  
    private string _exception_type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exception_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string exception_type
    {
      get { return _exception_type; }
      set { _exception_type = value; }
    }
    private string _message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private Exception_PB _cause = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cause", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Exception_PB cause
    {
      get { return _cause; }
      set { _cause = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }

  [DataContract, global::ProtoBuf.ProtoContract(Name = @"Time_PB")]
  public partial class Time_PB : global::ProtoBuf.IExtensible
  {
    public Time_PB() {}
    
    private int _hours = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hours", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int hours
    {
      get { return _hours; }
      set { _hours = value; }
    }
    private int _minutes = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"minutes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int minutes
    {
      get { return _minutes; }
      set { _minutes = value; }
    }
    private int _seconds = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int seconds
    {
      get { return _seconds; }
      set { _seconds = value; }
    }
    private int _utc_offset = default(int);
    [global::System.Obsolete, global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"utc_offset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int utc_offset
    {
      get { return _utc_offset; }
      set { _utc_offset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }

  [DataContract, global::ProtoBuf.ProtoContract(Name = @"Date_PB")]
  public partial class Date_PB : global::ProtoBuf.IExtensible
  {
    public Date_PB() {}
    
    private int _year = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int year
    {
      get { return _year; }
      set { _year = value; }
    }
    private int _month = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"month", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int month
    {
      get { return _month; }
      set { _month = value; }
    }
    private int _day = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"day", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int day
    {
      get { return _day; }
      set { _day = value; }
    }
    private Time_PB _time = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Time_PB time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClientDeviceType_PB")]
    public enum ClientDeviceType_PB
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ANDROID", Value=0)]
      ANDROID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"IOS", Value=1)]
      IOS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WINDOWS_PHONE", Value=2)]
      WINDOWS_PHONE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BROWSER", Value=3)]
      BROWSER = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DayOfWeekType_PB")]
    public enum DayOfWeekType_PB
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DAY_OF_WEEK_NOT_SET", Value=0)]
      DAY_OF_WEEK_NOT_SET = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUNDAY", Value=1)]
      SUNDAY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONDAY", Value=2)]
      MONDAY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TUESDAY", Value=3)]
      TUESDAY = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEDNESDAY", Value=4)]
      WEDNESDAY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THURSDAY", Value=5)]
      THURSDAY = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRIDAY", Value=6)]
      FRIDAY = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SATURDAY", Value=7)]
      SATURDAY = 7
    }
  
}